### PR TITLE
Add support to set custom sendingIcon

### PR DESCRIPTION
**Pull request by abhisunkewar**
### What does it do?

Add parameter `sendingIcon` to `ChatTheme`.  

### Why is it needed?

A more customizable `ChatTheme` makes the library flexible.

### How to test it?

Pass the desired `Widget` as an argument to `sendingIcon` of `DefaultChatTheme`.

### Related issues/PRs

Let us know if this is related to any issue/pull request.

### CODE REVIEW

**Comment by demchenkoalex** [comment]
Hi @abhisunkewar. I don't get the use case for it. What you will present there?

**Comment by abhisunkewar** [comment]
Hey @demchenkoalex, I was working on a chat app of my own and didn't really like the `CircularProgressIndicator` for  messages with status `sending`. I'm sure the community will appreciate a little more customization in that regard.

**Comment by demchenkoalex** [comment]
I understand that. But what you didn't actually like? That it is there at all? or color? or its shape? What would you put instead? Just trying to understand the use case. There is at most 10 points of space for the widget there.

**Comment by abhisunkewar** [comment]
The issue I had was when there are more than 2 messages are being sent, the progress indicator kinda becomes distracting and unpleasant to the eyes.

I ended up adding a clock icon similar to WhatsApp's.

**Review by demchenkoalex — APPROVED** [review]

**Comment by demchenkoalex** [comment]
Thanks for the PR!

**Pull request merged**
