### PR TITLE
Display system messages

### PR DESCRIPTION
**Pull request by felixgabler**
### What does it do?

Show system messages for things like 'YXZ joined the chat'.

### Why is it needed?

Using custom messages for such use cases is not great because they are not centered. This makes system messages a first class concept.

### Related issues/PRs

[Types PR](https://github.com/flyerhq/flutter_chat_types/pull/26#issuecomment-1203012479)

Built on top of https://github.com/flyerhq/flutter_chat_ui/pull/303. Wait for it before you review and merge.

### CODE REVIEW

**Comment by demchenkoalex** [comment]
Thanks for the rebase! I am not sure about this implementation, I think system message should be part of the animated list like any other message? Otherwise it will just drop in randomly.

**Comment by felixgabler** [comment]
> Thanks for the rebase! I am not sure about this implementation, I think system message should be part of the animated list like any other message? Otherwise it will just drop in randomly.

They are part of the animated list though. The `Message` widget does not perform animation critical functions but just provides avatar, name, border radius etc. For system messages, we really want to prevent all of that and place it centered.

The only things that we could think about adding is gesture detection (although I don't know how useful that would be) and maybe visibility detection (also not sure how useful). In any case, fitting the system messages into the constraints of the `Message` widget would be a mistake imho.

**Comment by demchenkoalex** [comment]
OK, my mistake :D

**Comment by felixgabler** [comment]
Hey @demchenkoalex, is there anything missing before we can merge?

**Comment by demchenkoalex** [comment]
I don't think so, will take a look

**Comment by demchenkoalex** [comment]
will resolve this ASAP

**Review by demchenkoalex — APPROVED** [review]

**Comment by demchenkoalex** [comment]
Thanks for the PR!

**Pull request merged**
