### PR TITLE
Add options to open preview on title or image tap

### PR DESCRIPTION
**Pull request by felixgabler**
### What does it do?

You can now specify options to enable the tap-to-open behavior from yesterdays PR.

### Why is it needed?

No other way of configuring this yet.

### How to test it?

Provide information about the environment and the path to verify the behavior.

### Related issues/PRs

[Let us know if this is related to any issue/pull request.](https://github.com/flyerhq/flutter_link_previewer/pull/39)

### CODE REVIEW

**Comment by demchenkoalex** [comment]
Not that familiar with Flutter, but is there a way to pass like all LinkPreview properties somehow? In React Native I would pass props: LinkPreviewProps and then just do <LinkPreview {...props} /> and user can configure everything.. here we adding two props, but still some are not configurable, and if we add more props, we need to copy them over and over.. don't like Dart because of that :D

**Comment by felixgabler** [comment]
Unfortunately, that is not possible. We could however create a configuration object that gets passed down to simplify all future configuration. Do you want me to do that here?

**Comment by demchenkoalex** [comment]
Yes, please. I will see how it is done and will try to apply that pattern in the future.

**Comment by felixgabler** [comment]
I just pulled them into one config object which people sometimes do so that they don't have to change many files when adding or removing. Basically, like context. I wish there was something like `...props`. Makes me miss React :(

**Review by demchenkoalex — APPROVED** [review]

**Comment by demchenkoalex** [comment]
Thanks for the PR!

**Pull request merged**
