### PR TITLE
Feature/animation

### PR DESCRIPTION
**Pull request by demchenkoalex**

### CODE REVIEW

**Comment by jlubeck** [comment]
Any estimates on when this will be merged to master? Thanks a bunch for all your hard work!

**Comment by demchenkoalex** [comment]
As soon as I figure out how to connect this to Firebase, which I'm doing this week :)

**Comment by demchenkoalex** [comment]
Released in [v1.1](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.1.0).

**Comment by LanceOwide** [comment]
Thanks Alex! Very excited to try it out today.

**Pull request merged**
