### PR TITLE
Allow specifying text message matchers per message

### PR DESCRIPTION
**Pull request by jld3103**
### What does it do?

Add fields to allow specifying additional matchers per text message.

### Why is it needed?

See https://github.com/flyerhq/flutter_chat_ui/pull/337#issuecomment-1295803184

### Related issues/PRs

https://github.com/flyerhq/flutter_chat_ui/pull/337

### CODE REVIEW

**Comment by demchenkoalex** [comment]
I don't understand still, how do you pass these matchers? you render `Chat` component and there is nothing passed to chat except `TextMessageOptions`.  Do you somehow render custom text message and use text message from the package?

**Comment by jld3103** [comment]
Ah sorry, I'm using the `textMessageBuilder` to do this.

**Comment by demchenkoalex** [comment]
so that means you do something like `textMessageBuilder` and then you put there `TextMessage` from the lib right? And you're saying that matchers go based on metadata. So in the `textMessageBuilder` you have access to the metadata and the `TextMessage` widget, so why options does not work? you just create options based on the `metadata`, pass matchers there and it works, no?

**Comment by jld3103** [comment]
Oh I think I messed up. I just thought the options were coming from a layer above where I dom't have access to the message itself. My bad.

**Pull request closed without merging**
