### PR TITLE
[Feature] directionality and localization

### PR DESCRIPTION
**Pull request by Faaatman**
### What does it do?

Implement directionality where if the text direction is RTL everything moves according to it.
I also added Arabic Localization as `ChatL10nAr`

### Why is it needed?

The chat to be useable in RTL languages the bubbles and buttons need to be swapped by the Y-axis

### How to test it?

Wrap the `Chat` widget with `Directionality` and change TextDirection from ltr to rtl to see the effect.
ex:
```dart
Directionality(
    textDirection: TextDirection.rtl,
    child: Chat()
)
```

### CODE REVIEW

**Comment by demchenkoalex** [comment]
Thanks for the PR!

**Comment by Yahllil** [comment]
This is working great for the input text field, but when setting the Directionality to RTL, the message bubbles themself go the opposite direction.
Instead of aligning the outgoing messages to the right like a chat app, it aligns the incoming messages to the right.

Is there any way of changing the direction of the bubbles, while keeping the input field RTL?

**Comment by demchenkoalex** [comment]
Hey @Yahllil, sorry missed this comment. I am not 100% sure how chats are rendered in Arabic countries for example, they still have outgoing messages on the right? If so, I think we just need to disable RTL for messages alignment for everybody and that's it.

**Comment by Yahllil** [comment]
Hi @demchenkoalex Yes, in an Hebrew/Arabic chat messages (or any other RTL), the bubbles are still on the right. It is just the `textDirection` and `textAlignment` that needs to be set to RTL.

**Comment by demchenkoalex** [comment]
Will do! Thanks for pointing this out!

**Comment by Yahllil** [comment]
> Will do! Thanks for pointing this out!

@demchenkoalex Thank you! Please comment on this thread once it is merged so I can upgrade the package in the project :)
Thanks again!

**Comment by demchenkoalex** [comment]
Fix is on `main`, will be included in the new release, `v1.6.2`

**Comment by Faaatman** [comment]
Hello @demchenkoalex,
I hope you're doing great! I'm sorry for this confusion. I tested changing my phone language to Arabic and opened Whatsapp, the chat bubbles are inverted, where the sent ones are on the left and the received ones are on the right.
Can we have a bool to change the direction of the bubble so that it can be compatible with everyone?
Thank you.

**Comment by Yahllil** [comment]
> Hello @demchenkoalex,
> I hope you're doing great! I'm sorry for this confusion. I tested changing my phone language to Arabic and opened Whatsapp, the chat bubbles are inverted, where the sent ones are on the left and the received ones are on the right.
> Can we have a bool to change the direction of the bubble so that it can be compatible with everyone?
> Thank you.

Hi @demchenkoalex I don't know about Arabic chat, but in Hebrew for example, the WhatsApp chat's sent messages are aligned to the right, so @demchenkoalex 's fix was crucial for implementing RTL Hebrew chat

**Comment by demchenkoalex** [comment]
I checked WhatsApp, iMessages, Telegram, Messenger on Arabic and most of them were normally aligned (not reverted) so I though that was more like a standard. I will see about a prop.

**Comment by demchenkoalex** [comment]
@Faaatman sorry for the confusion. Added `bubbleRtlAlignment` which is default to right, you will want to set it to left. It is on main, will be released shortly.

**Pull request merged**
