### PR TITLE
introduce imageProviderBuilder

### PR DESCRIPTION
**Pull request by marinkobabic**
provide option for custom imageProviderBuilder which provides a lot of possibilities

### CODE REVIEW

**Comment by marinkobabic** [comment]
Any feedback here?

Without this feature I'm not able without overriding the whole image message to support offline access of the chat.

**Comment by marinkobabic** [comment]
If you have another idea how to provide offline support, I'm open for any suggestions. Otherwise please just merge the pull request. Having custom builder provides the most flexibility

**Comment by marinkobabic** [comment]
Any progress since weekend? 😄

**Comment by marinkobabic** [comment]
Maybe this issue can be then solved also https://github.com/flyerhq/flutter_chat_ui/issues/308

**Comment by marinkobabic** [comment]
Would be great if you could have a look at the pull request. Happy new year by the way. 😄

**Comment by 4mitabh** [comment]
I think it would be fantastic if we could get this merged.
 I can think of tons of possibilities that would come with an imageProviderBuilder.

With features like caching, offline image access, loading images from memory, and loading images from bundled assets, the potential for new use cases is endless. 

Let's merge this please!

**Review by demchenkoalex — APPROVED** [review]

**Pull request merged**
