### PR TITLE
add slidableMessageBuilder/2 optional method

### PR DESCRIPTION
**Pull request by leeyisoft**
Add optional methods slidableMessageBuilder/2

Use it like this:

```
            Chat(
              user: logic.cuser,
              messages: messages,
              ...
              slidableMessageBuilder: (types.Message msg, Widget msgWidget) {
                return GestureDetector(
                  onPanEnd: (DragEndDetails details) {
                    updateQuoteMessage(msg);
                  },
                  child: msgWidget,
                );
              },
              ...
```

_autoScrollIndexById modified to chatMessageAutoScrollIndexById, set to global variables, easy reference to reuse

_autoScrollIndexById 修改为 chatMessageAutoScrollIndexById，设置为全局变量，便于引用方复用

```
    return GestureDetector(
      onTap: () {
        debugPrint("> on quoteMsg_onTap");
        ChatLogic loigc = Get.find();
        int msgIdIndex = chatMessageAutoScrollIndexById[quoteMsg.id] ?? 0;
        if (msgIdIndex > 0) {
          loigc.state.scrollController.scrollToIndex(
            msgIdIndex,
            duration: const Duration(milliseconds: 250),
          );
        } else {
          // 数据不存在
        }
```

### CODE REVIEW

**Review by denes16 — APPROVED** [review]

**Comment by leeyisoft** [comment]
Accidentally triggered the "requested a review" @denes16 

I have nothing to modify at the moment, hope this submission can be merged into the main branch

**Comment by demchenkoalex** [comment]
is this ready?

**Comment by leeyisoft** [comment]
> is this ready?

This PR, which I applied to imboyfluter (https://github.com/imboy-pub/imboy-flutter), runs normally on the real machine of Android iOS macOS, I think it is ready, you see what else needs to be adjusted?

**Comment by demchenkoalex** [comment]
Thanks for the PR!

**Pull request merged**
