### PR TITLE
feat: add onMessageVisibilityChanged handler

### PR DESCRIPTION
**Pull request by felixgabler**
### What does it do?

Added a callback for when messages become visible or scroll out of view.

### Why is it needed?

This can be used to mark messages as seen when they were actually seen. The next step will be scrolling to the last unseen message.

### How to test it?

Open the example app and look at the logger. I added a debug log message for when a message's visibility changes.

### Related issues/PRs

First part of #179 

### Question

Should I add this to the documentation or wait until I also create a PR for scroll to message?

### CODE REVIEW

**Comment by demchenkoalex** [comment]
Hey, regarding documentation, I can update it when everything's ready, but wanted to ask one question - do you have experience with unit tests in Flutter? We are working with Google to get the Flutter Favourite badge and one of the requirements is to cover new functionality with unit tests, might be cool to test the visibility widget in work. But if not, that's ok too, we will cover something else :)

**Comment by felixgabler** [comment]
Yeah, I have experience with integration, widget and unit tests. But you mean widget tests, right? Not sure how to unit test a widget.

I can definitely help you in any case. Just let me know which area specifically to cover and whether you have any testing guidelines.

**Comment by felixgabler** [comment]
Please let me know if the test I added is what you were looking for

**Review by demchenkoalex — APPROVED** [review]

**Comment by demchenkoalex** [comment]
No testing guidelines, but I think I might learn from you a bit, cause I am not really experienced in Flutter testing, so thank you for adding this!

**Comment by GustekDev** [comment]
Hi.

Do you plan to make a release with this change or are you holding off until #179 is completed?

**Comment by demchenkoalex** [comment]
Hey, this project was affected by war since I am from Ukraine and now I am away from computer until the end of March, I will try to come back ASAP.

**Comment by GustekDev** [comment]
Thank you for your response. 
No rush.
Stay safe.

**Pull request merged**
