### PR TITLE
pass new parameter for utc support

### PR DESCRIPTION
**Pull request by marinkobabic**
https://github.com/flyerhq/flutter_chat_ui/issues/334

### CODE REVIEW

**Comment by jld3103** [comment]
Maybe it's better to just pass a `DateTime` to the library in the first place? I found this very confusing at first since how it's right now is not really a common pattern.

**Comment by marinkobabic** [comment]
I agree. This is what I'm normally facing in other projects instead of the epoch time in milliseconds. It may be hard to introduce this change because of backward compatibility.

**Comment by jld3103** [comment]
Hm yes, but also it's not that huge I imagine and a very good update on the quality of the library.

**Comment by marinkobabic** [comment]
Any comments on this by the owner of the library?

**Comment by marinkobabic** [comment]
@demchenkoalex any way to merge this change as well? Thanks in advance

**Comment by demchenkoalex** [comment]
Hi, I just started to look at the repo :) I will get here. From a quick glance I would prefer `DateTime` solution, so maybe I will do one release with smaller things I will find and the other one, breaking, using `DateTime`.

**Comment by demchenkoalex** [comment]
OK, merging this, but I will be in favour of releasing `DateTime` breaking change later. Thanks for the PR!

**Comment by marinkobabic** [comment]
thats clear, thx :-)

**Pull request merged**
